/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const ListId = IDL.Nat;
export const List = IDL.Record({
  'id' : ListId,
  'name' : IDL.Text,
  'important' : IDL.Bool,
  'urgent' : IDL.Bool,
  'quadrant' : IDL.Bool,
});
export const UserTier = IDL.Variant({
  'gold' : IDL.Null,
  'diamond' : IDL.Null,
  'basic' : IDL.Null,
  'silver' : IDL.Null,
});
export const UserProfile = IDL.Record({
  'earningsEnabled' : IDL.Bool,
  'name' : IDL.Text,
  'tier' : UserTier,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'getAllUserLists' : IDL.Func([], [IDL.Opt(IDL.Vec(List))], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'maybeInitializeAllQuadrants' : IDL.Func([], [IDL.Opt(IDL.Vec(List))], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const ListId = IDL.Nat;
  const List = IDL.Record({
    'id' : ListId,
    'name' : IDL.Text,
    'important' : IDL.Bool,
    'urgent' : IDL.Bool,
    'quadrant' : IDL.Bool,
  });
  const UserTier = IDL.Variant({
    'gold' : IDL.Null,
    'diamond' : IDL.Null,
    'basic' : IDL.Null,
    'silver' : IDL.Null,
  });
  const UserProfile = IDL.Record({
    'earningsEnabled' : IDL.Bool,
    'name' : IDL.Text,
    'tier' : UserTier,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'getAllUserLists' : IDL.Func([], [IDL.Opt(IDL.Vec(List))], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'maybeInitializeAllQuadrants' : IDL.Func([], [IDL.Opt(IDL.Vec(List))], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  });
};

export const init = ({ IDL }) => { return []; };