/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface UserMetadata {
    principal: Principal;
    isAdmin: boolean;
    profile?: UserProfile;
}
export interface TierLimitsConfig {
    gold: TierLimits;
    diamond: TierLimits;
    basic: TierLimits;
    silver: TierLimits;
}
export interface TaskUpdateInput {
    title: string;
    isLongTask: boolean;
    order: bigint;
    completed: boolean;
    description: string;
    important: boolean;
    urgent: boolean;
    listId: ListId;
}
export interface Task {
    id: TaskId;
    weight: number;
    title: string;
    isLongTask: boolean;
    order: bigint;
    completed: boolean;
    description: string;
    important: boolean;
    urgent: boolean;
    listId: ListId;
}
export interface SpendPreset {
    id: bigint;
    name: string;
    category: string;
    amount: number;
}
export interface SpendInput {
    category: string;
    amount: number;
    spendType: SpendType;
}
export interface PayrollRecord {
    total: bigint;
    submitted: boolean;
    date: bigint;
    details: {
        morning: bigint;
        evening: bigint;
        priorities: bigint;
    };
}
export interface TierLimits {
    maxCustomLists?: bigint;
    maxTasks?: bigint;
    maxRoutines?: bigint;
}
export interface MorningRoutine {
    id: RoutineId;
    weight: bigint;
    strikeCount: bigint;
    order: bigint;
    text: string;
    completed: boolean;
    section: RoutineSection;
    streakCount: bigint;
}
export interface TaskCreateInput {
    title: string;
    isLongTask: boolean;
    order: bigint;
    description: string;
    important: boolean;
    urgent: boolean;
    listId: ListId;
}
export interface UserStorageBreakdown {
    principal: Principal;
    routineCount: bigint;
    taskCount: bigint;
    estimatedSizeBytes: bigint;
}
export interface SpendRecord {
    id: SpendId;
    date: bigint;
    category: string;
    amount: number;
    spendType: SpendType;
}
export type TaskId = bigint;
export interface StorageMetrics {
    totalTasks: bigint;
    estimatedHeapMemoryBytes: bigint;
    totalRoutines: bigint;
    totalUsers: bigint;
    estimatedStableMemoryBytes: bigint;
}
export type ListId = bigint;
export type RoutineId = bigint;
export type SpendId = bigint;
export interface MonetarySettings {
    maxDailyPriorities: bigint;
    maxMorningRoutine: bigint;
    maxMoneyPerDay: bigint;
    totalBalance: bigint;
    maxEveningRoutine: bigint;
}
export interface List {
    id: ListId;
    name: string;
    important: boolean;
    urgent: boolean;
    quadrant: boolean;
}
export interface UserProfile {
    earningsEnabled: boolean;
    name: string;
    tier: UserTier;
    email?: string;
}
export enum RoutineSection {
    top = "top",
    bottom = "bottom"
}
export enum SpendType {
    normal = "normal",
    preDeducted = "preDeducted"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export enum UserTier {
    gold = "gold",
    diamond = "diamond",
    basic = "basic",
    silver = "silver"
}
export interface backendInterface {
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    addPayroll(dailyIncome: bigint): Promise<bigint>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    completeMorningRoutine(id: RoutineId, completed: boolean): Promise<void>;
    completeTask(id: TaskId, completed: boolean): Promise<void>;
    createList(name: string): Promise<ListId>;
    createMorningRoutine(text: string, section: RoutineSection): Promise<RoutineId>;
    createPreset(preset: SpendPreset): Promise<bigint>;
    createSpend(input: SpendInput): Promise<string>;
    createTask(input: TaskCreateInput): Promise<TaskId>;
    deleteList(id: ListId): Promise<void>;
    deleteMorningRoutine(id: RoutineId): Promise<void>;
    deletePreset(id: bigint): Promise<void>;
    deleteSpend(spendId: SpendId): Promise<void>;
    deleteTask(id: TaskId): Promise<void>;
    editPayrollLog(date: bigint, updatedTotal: bigint): Promise<void>;
    ensureAllQuadrants(): Promise<void>;
    getAllLists(): Promise<Array<List>>;
    getAllMorningRoutines(): Promise<Array<MorningRoutine>>;
    getAllSpendPresets(): Promise<Array<SpendPreset>>;
    getAllSpends(): Promise<Array<SpendRecord>>;
    getAllTasks(): Promise<Array<Task>>;
    getAllTasksByList(listId: ListId): Promise<Array<Task>>;
    getAllTierLimits(): Promise<TierLimitsConfig>;
    getAllUserMetadata(): Promise<Array<[Principal, UserProfile]>>;
    getAllUserMetadataWithRoles(): Promise<Array<UserMetadata>>;
    getAllUserStorageBreakdowns(): Promise<Array<UserStorageBreakdown>>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getDefaultOrder(): Promise<bigint>;
    getDefaultPosition(): Promise<bigint>;
    getEarningsEnabled(): Promise<boolean>;
    getEstimatedMemoryUsage(): Promise<{
        stableSize: bigint;
        heapSize: bigint;
    }>;
    getList(id: ListId): Promise<List>;
    getMonetarySettings(): Promise<MonetarySettings>;
    getMorningRoutine(id: RoutineId): Promise<MorningRoutine>;
    getMorningRoutinesBySection(section: RoutineSection): Promise<Array<MorningRoutine>>;
    getOverallStorageMetrics(): Promise<StorageMetrics>;
    getPayrollHistory(): Promise<Array<PayrollRecord>>;
    getPreset(id: bigint): Promise<SpendPreset | null>;
    getRoutineAndTaskStorageBreakdown(): Promise<{
        tasks: {
            total: bigint;
            userBreakdowns: Array<bigint>;
        };
        routines: {
            total: bigint;
            userBreakdowns: Array<bigint>;
        };
    }>;
    getRoutineStorageBreakdown(): Promise<{
        total: bigint;
        userBreakdowns: Array<bigint>;
    }>;
    getTask(id: TaskId): Promise<Task>;
    getTaskStorageBreakdown(): Promise<{
        total: bigint;
        userBreakdowns: Array<bigint>;
    }>;
    getTopUsersByStorage(limit: bigint): Promise<Array<UserStorageBreakdown>>;
    getTotalStorageUsed(): Promise<bigint>;
    getTotalUsers(): Promise<bigint>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    isCallerAdmin(): Promise<boolean>;
    moveTaskToList(taskId: TaskId, destinationListId: ListId, newPosition: bigint): Promise<void>;
    promoteToAdmin(target: Principal): Promise<void>;
    removeAdmin(target: Principal): Promise<void>;
    resetNewDay(completedRoutineIds: Array<RoutineId>): Promise<void>;
    resetSkippedDay(): Promise<void>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    saveMonetarySettings(settings: MonetarySettings): Promise<void>;
    setUserTier(targetUser: Principal, newTier: UserTier): Promise<void>;
    submitPayrollLog(date: bigint): Promise<bigint>;
    toggleEarningsSystem(enabled: boolean): Promise<boolean>;
    updateMorningRoutine(id: RoutineId, text: string, section: RoutineSection): Promise<void>;
    updatePreset(id: bigint, updatedPreset: SpendPreset): Promise<void>;
    updateRoutineItemPosition(routineId: RoutineId, positionIndex: bigint): Promise<void>;
    updateTask(id: TaskId, updatedTask: TaskUpdateInput): Promise<void>;
    updateTierLimits(tier: UserTier, newLimits: TierLimits): Promise<void>;
}
import type { MorningRoutine as _MorningRoutine, RoutineId as _RoutineId, RoutineSection as _RoutineSection, SpendId as _SpendId, SpendInput as _SpendInput, SpendPreset as _SpendPreset, SpendRecord as _SpendRecord, SpendType as _SpendType, TierLimits as _TierLimits, TierLimitsConfig as _TierLimitsConfig, UserMetadata as _UserMetadata, UserProfile as _UserProfile, UserRole as _UserRole, UserTier as _UserTier } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async addPayroll(arg0: bigint): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.addPayroll(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addPayroll(arg0);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async completeMorningRoutine(arg0: RoutineId, arg1: boolean): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.completeMorningRoutine(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.completeMorningRoutine(arg0, arg1);
            return result;
        }
    }
    async completeTask(arg0: TaskId, arg1: boolean): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.completeTask(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.completeTask(arg0, arg1);
            return result;
        }
    }
    async createList(arg0: string): Promise<ListId> {
        if (this.processError) {
            try {
                const result = await this.actor.createList(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createList(arg0);
            return result;
        }
    }
    async createMorningRoutine(arg0: string, arg1: RoutineSection): Promise<RoutineId> {
        if (this.processError) {
            try {
                const result = await this.actor.createMorningRoutine(arg0, to_candid_RoutineSection_n3(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createMorningRoutine(arg0, to_candid_RoutineSection_n3(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async createPreset(arg0: SpendPreset): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.createPreset(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createPreset(arg0);
            return result;
        }
    }
    async createSpend(arg0: SpendInput): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.createSpend(to_candid_SpendInput_n5(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createSpend(to_candid_SpendInput_n5(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async createTask(arg0: TaskCreateInput): Promise<TaskId> {
        if (this.processError) {
            try {
                const result = await this.actor.createTask(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createTask(arg0);
            return result;
        }
    }
    async deleteList(arg0: ListId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteList(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteList(arg0);
            return result;
        }
    }
    async deleteMorningRoutine(arg0: RoutineId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteMorningRoutine(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteMorningRoutine(arg0);
            return result;
        }
    }
    async deletePreset(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deletePreset(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deletePreset(arg0);
            return result;
        }
    }
    async deleteSpend(arg0: SpendId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteSpend(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteSpend(arg0);
            return result;
        }
    }
    async deleteTask(arg0: TaskId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteTask(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteTask(arg0);
            return result;
        }
    }
    async editPayrollLog(arg0: bigint, arg1: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.editPayrollLog(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.editPayrollLog(arg0, arg1);
            return result;
        }
    }
    async ensureAllQuadrants(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.ensureAllQuadrants();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.ensureAllQuadrants();
            return result;
        }
    }
    async getAllLists(): Promise<Array<List>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllLists();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllLists();
            return result;
        }
    }
    async getAllMorningRoutines(): Promise<Array<MorningRoutine>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllMorningRoutines();
                return from_candid_vec_n9(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllMorningRoutines();
            return from_candid_vec_n9(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllSpendPresets(): Promise<Array<SpendPreset>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllSpendPresets();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllSpendPresets();
            return result;
        }
    }
    async getAllSpends(): Promise<Array<SpendRecord>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllSpends();
                return from_candid_vec_n14(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllSpends();
            return from_candid_vec_n14(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllTasks(): Promise<Array<Task>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllTasks();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllTasks();
            return result;
        }
    }
    async getAllTasksByList(arg0: ListId): Promise<Array<Task>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllTasksByList(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllTasksByList(arg0);
            return result;
        }
    }
    async getAllTierLimits(): Promise<TierLimitsConfig> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllTierLimits();
                return from_candid_TierLimitsConfig_n19(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllTierLimits();
            return from_candid_TierLimitsConfig_n19(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllUserMetadata(): Promise<Array<[Principal, UserProfile]>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllUserMetadata();
                return from_candid_vec_n24(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllUserMetadata();
            return from_candid_vec_n24(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllUserMetadataWithRoles(): Promise<Array<UserMetadata>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllUserMetadataWithRoles();
                return from_candid_vec_n31(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllUserMetadataWithRoles();
            return from_candid_vec_n31(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllUserStorageBreakdowns(): Promise<Array<UserStorageBreakdown>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllUserStorageBreakdowns();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllUserStorageBreakdowns();
            return result;
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n34(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n34(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n35(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n35(this._uploadFile, this._downloadFile, result);
        }
    }
    async getDefaultOrder(): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.getDefaultOrder();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDefaultOrder();
            return result;
        }
    }
    async getDefaultPosition(): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.getDefaultPosition();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDefaultPosition();
            return result;
        }
    }
    async getEarningsEnabled(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.getEarningsEnabled();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getEarningsEnabled();
            return result;
        }
    }
    async getEstimatedMemoryUsage(): Promise<{
        stableSize: bigint;
        heapSize: bigint;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.getEstimatedMemoryUsage();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getEstimatedMemoryUsage();
            return result;
        }
    }
    async getList(arg0: ListId): Promise<List> {
        if (this.processError) {
            try {
                const result = await this.actor.getList(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getList(arg0);
            return result;
        }
    }
    async getMonetarySettings(): Promise<MonetarySettings> {
        if (this.processError) {
            try {
                const result = await this.actor.getMonetarySettings();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMonetarySettings();
            return result;
        }
    }
    async getMorningRoutine(arg0: RoutineId): Promise<MorningRoutine> {
        if (this.processError) {
            try {
                const result = await this.actor.getMorningRoutine(arg0);
                return from_candid_MorningRoutine_n10(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMorningRoutine(arg0);
            return from_candid_MorningRoutine_n10(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMorningRoutinesBySection(arg0: RoutineSection): Promise<Array<MorningRoutine>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMorningRoutinesBySection(to_candid_RoutineSection_n3(this._uploadFile, this._downloadFile, arg0));
                return from_candid_vec_n9(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMorningRoutinesBySection(to_candid_RoutineSection_n3(this._uploadFile, this._downloadFile, arg0));
            return from_candid_vec_n9(this._uploadFile, this._downloadFile, result);
        }
    }
    async getOverallStorageMetrics(): Promise<StorageMetrics> {
        if (this.processError) {
            try {
                const result = await this.actor.getOverallStorageMetrics();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getOverallStorageMetrics();
            return result;
        }
    }
    async getPayrollHistory(): Promise<Array<PayrollRecord>> {
        if (this.processError) {
            try {
                const result = await this.actor.getPayrollHistory();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPayrollHistory();
            return result;
        }
    }
    async getPreset(arg0: bigint): Promise<SpendPreset | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getPreset(arg0);
                return from_candid_opt_n37(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPreset(arg0);
            return from_candid_opt_n37(this._uploadFile, this._downloadFile, result);
        }
    }
    async getRoutineAndTaskStorageBreakdown(): Promise<{
        tasks: {
            total: bigint;
            userBreakdowns: Array<bigint>;
        };
        routines: {
            total: bigint;
            userBreakdowns: Array<bigint>;
        };
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.getRoutineAndTaskStorageBreakdown();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getRoutineAndTaskStorageBreakdown();
            return result;
        }
    }
    async getRoutineStorageBreakdown(): Promise<{
        total: bigint;
        userBreakdowns: Array<bigint>;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.getRoutineStorageBreakdown();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getRoutineStorageBreakdown();
            return result;
        }
    }
    async getTask(arg0: TaskId): Promise<Task> {
        if (this.processError) {
            try {
                const result = await this.actor.getTask(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTask(arg0);
            return result;
        }
    }
    async getTaskStorageBreakdown(): Promise<{
        total: bigint;
        userBreakdowns: Array<bigint>;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.getTaskStorageBreakdown();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTaskStorageBreakdown();
            return result;
        }
    }
    async getTopUsersByStorage(arg0: bigint): Promise<Array<UserStorageBreakdown>> {
        if (this.processError) {
            try {
                const result = await this.actor.getTopUsersByStorage(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTopUsersByStorage(arg0);
            return result;
        }
    }
    async getTotalStorageUsed(): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.getTotalStorageUsed();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTotalStorageUsed();
            return result;
        }
    }
    async getTotalUsers(): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.getTotalUsers();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTotalUsers();
            return result;
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n34(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n34(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async moveTaskToList(arg0: TaskId, arg1: ListId, arg2: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.moveTaskToList(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.moveTaskToList(arg0, arg1, arg2);
            return result;
        }
    }
    async promoteToAdmin(arg0: Principal): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.promoteToAdmin(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.promoteToAdmin(arg0);
            return result;
        }
    }
    async removeAdmin(arg0: Principal): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.removeAdmin(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.removeAdmin(arg0);
            return result;
        }
    }
    async resetNewDay(arg0: Array<RoutineId>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.resetNewDay(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.resetNewDay(arg0);
            return result;
        }
    }
    async resetSkippedDay(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.resetSkippedDay();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.resetSkippedDay();
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(to_candid_UserProfile_n38(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(to_candid_UserProfile_n38(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async saveMonetarySettings(arg0: MonetarySettings): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveMonetarySettings(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveMonetarySettings(arg0);
            return result;
        }
    }
    async setUserTier(arg0: Principal, arg1: UserTier): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setUserTier(arg0, to_candid_UserTier_n40(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setUserTier(arg0, to_candid_UserTier_n40(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async submitPayrollLog(arg0: bigint): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.submitPayrollLog(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitPayrollLog(arg0);
            return result;
        }
    }
    async toggleEarningsSystem(arg0: boolean): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.toggleEarningsSystem(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.toggleEarningsSystem(arg0);
            return result;
        }
    }
    async updateMorningRoutine(arg0: RoutineId, arg1: string, arg2: RoutineSection): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateMorningRoutine(arg0, arg1, to_candid_RoutineSection_n3(this._uploadFile, this._downloadFile, arg2));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateMorningRoutine(arg0, arg1, to_candid_RoutineSection_n3(this._uploadFile, this._downloadFile, arg2));
            return result;
        }
    }
    async updatePreset(arg0: bigint, arg1: SpendPreset): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updatePreset(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updatePreset(arg0, arg1);
            return result;
        }
    }
    async updateRoutineItemPosition(arg0: RoutineId, arg1: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateRoutineItemPosition(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateRoutineItemPosition(arg0, arg1);
            return result;
        }
    }
    async updateTask(arg0: TaskId, arg1: TaskUpdateInput): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateTask(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateTask(arg0, arg1);
            return result;
        }
    }
    async updateTierLimits(arg0: UserTier, arg1: TierLimits): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateTierLimits(to_candid_UserTier_n40(this._uploadFile, this._downloadFile, arg0), to_candid_TierLimits_n42(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateTierLimits(to_candid_UserTier_n40(this._uploadFile, this._downloadFile, arg0), to_candid_TierLimits_n42(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
}
function from_candid_MorningRoutine_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _MorningRoutine): MorningRoutine {
    return from_candid_record_n11(_uploadFile, _downloadFile, value);
}
function from_candid_RoutineSection_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _RoutineSection): RoutineSection {
    return from_candid_variant_n13(_uploadFile, _downloadFile, value);
}
function from_candid_SpendRecord_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _SpendRecord): SpendRecord {
    return from_candid_record_n16(_uploadFile, _downloadFile, value);
}
function from_candid_SpendType_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _SpendType): SpendType {
    return from_candid_variant_n18(_uploadFile, _downloadFile, value);
}
function from_candid_TierLimitsConfig_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _TierLimitsConfig): TierLimitsConfig {
    return from_candid_record_n20(_uploadFile, _downloadFile, value);
}
function from_candid_TierLimits_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _TierLimits): TierLimits {
    return from_candid_record_n22(_uploadFile, _downloadFile, value);
}
function from_candid_UserMetadata_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserMetadata): UserMetadata {
    return from_candid_record_n33(_uploadFile, _downloadFile, value);
}
function from_candid_UserProfile_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserProfile): UserProfile {
    return from_candid_record_n27(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n36(_uploadFile, _downloadFile, value);
}
function from_candid_UserTier_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserTier): UserTier {
    return from_candid_variant_n29(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : from_candid_UserProfile_n26(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_SpendPreset]): SpendPreset | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _RoutineId;
    weight: bigint;
    strikeCount: bigint;
    order: bigint;
    text: string;
    completed: boolean;
    section: _RoutineSection;
    streakCount: bigint;
}): {
    id: RoutineId;
    weight: bigint;
    strikeCount: bigint;
    order: bigint;
    text: string;
    completed: boolean;
    section: RoutineSection;
    streakCount: bigint;
} {
    return {
        id: value.id,
        weight: value.weight,
        strikeCount: value.strikeCount,
        order: value.order,
        text: value.text,
        completed: value.completed,
        section: from_candid_RoutineSection_n12(_uploadFile, _downloadFile, value.section),
        streakCount: value.streakCount
    };
}
function from_candid_record_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _SpendId;
    date: bigint;
    category: string;
    amount: number;
    spendType: _SpendType;
}): {
    id: SpendId;
    date: bigint;
    category: string;
    amount: number;
    spendType: SpendType;
} {
    return {
        id: value.id,
        date: value.date,
        category: value.category,
        amount: value.amount,
        spendType: from_candid_SpendType_n17(_uploadFile, _downloadFile, value.spendType)
    };
}
function from_candid_record_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    gold: _TierLimits;
    diamond: _TierLimits;
    basic: _TierLimits;
    silver: _TierLimits;
}): {
    gold: TierLimits;
    diamond: TierLimits;
    basic: TierLimits;
    silver: TierLimits;
} {
    return {
        gold: from_candid_TierLimits_n21(_uploadFile, _downloadFile, value.gold),
        diamond: from_candid_TierLimits_n21(_uploadFile, _downloadFile, value.diamond),
        basic: from_candid_TierLimits_n21(_uploadFile, _downloadFile, value.basic),
        silver: from_candid_TierLimits_n21(_uploadFile, _downloadFile, value.silver)
    };
}
function from_candid_record_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    maxCustomLists: [] | [bigint];
    maxTasks: [] | [bigint];
    maxRoutines: [] | [bigint];
}): {
    maxCustomLists?: bigint;
    maxTasks?: bigint;
    maxRoutines?: bigint;
} {
    return {
        maxCustomLists: record_opt_to_undefined(from_candid_opt_n23(_uploadFile, _downloadFile, value.maxCustomLists)),
        maxTasks: record_opt_to_undefined(from_candid_opt_n23(_uploadFile, _downloadFile, value.maxTasks)),
        maxRoutines: record_opt_to_undefined(from_candid_opt_n23(_uploadFile, _downloadFile, value.maxRoutines))
    };
}
function from_candid_record_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    earningsEnabled: boolean;
    name: string;
    tier: _UserTier;
    email: [] | [string];
}): {
    earningsEnabled: boolean;
    name: string;
    tier: UserTier;
    email?: string;
} {
    return {
        earningsEnabled: value.earningsEnabled,
        name: value.name,
        tier: from_candid_UserTier_n28(_uploadFile, _downloadFile, value.tier),
        email: record_opt_to_undefined(from_candid_opt_n30(_uploadFile, _downloadFile, value.email))
    };
}
function from_candid_record_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    principal: Principal;
    isAdmin: boolean;
    profile: [] | [_UserProfile];
}): {
    principal: Principal;
    isAdmin: boolean;
    profile?: UserProfile;
} {
    return {
        principal: value.principal,
        isAdmin: value.isAdmin,
        profile: record_opt_to_undefined(from_candid_opt_n34(_uploadFile, _downloadFile, value.profile))
    };
}
function from_candid_tuple_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [Principal, _UserProfile]): [Principal, UserProfile] {
    return [
        value[0],
        from_candid_UserProfile_n26(_uploadFile, _downloadFile, value[1])
    ];
}
function from_candid_variant_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    top: null;
} | {
    bottom: null;
}): RoutineSection {
    return "top" in value ? RoutineSection.top : "bottom" in value ? RoutineSection.bottom : value;
}
function from_candid_variant_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    normal: null;
} | {
    preDeducted: null;
}): SpendType {
    return "normal" in value ? SpendType.normal : "preDeducted" in value ? SpendType.preDeducted : value;
}
function from_candid_variant_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    gold: null;
} | {
    diamond: null;
} | {
    basic: null;
} | {
    silver: null;
}): UserTier {
    return "gold" in value ? UserTier.gold : "diamond" in value ? UserTier.diamond : "basic" in value ? UserTier.basic : "silver" in value ? UserTier.silver : value;
}
function from_candid_variant_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_vec_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_SpendRecord>): Array<SpendRecord> {
    return value.map((x)=>from_candid_SpendRecord_n15(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<[Principal, _UserProfile]>): Array<[Principal, UserProfile]> {
    return value.map((x)=>from_candid_tuple_n25(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_UserMetadata>): Array<UserMetadata> {
    return value.map((x)=>from_candid_UserMetadata_n32(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_MorningRoutine>): Array<MorningRoutine> {
    return value.map((x)=>from_candid_MorningRoutine_n10(_uploadFile, _downloadFile, x));
}
function to_candid_RoutineSection_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: RoutineSection): _RoutineSection {
    return to_candid_variant_n4(_uploadFile, _downloadFile, value);
}
function to_candid_SpendInput_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: SpendInput): _SpendInput {
    return to_candid_record_n6(_uploadFile, _downloadFile, value);
}
function to_candid_SpendType_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: SpendType): _SpendType {
    return to_candid_variant_n8(_uploadFile, _downloadFile, value);
}
function to_candid_TierLimits_n42(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: TierLimits): _TierLimits {
    return to_candid_record_n43(_uploadFile, _downloadFile, value);
}
function to_candid_UserProfile_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserProfile): _UserProfile {
    return to_candid_record_n39(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function to_candid_UserTier_n40(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserTier): _UserTier {
    return to_candid_variant_n41(_uploadFile, _downloadFile, value);
}
function to_candid_record_n39(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    earningsEnabled: boolean;
    name: string;
    tier: UserTier;
    email?: string;
}): {
    earningsEnabled: boolean;
    name: string;
    tier: _UserTier;
    email: [] | [string];
} {
    return {
        earningsEnabled: value.earningsEnabled,
        name: value.name,
        tier: to_candid_UserTier_n40(_uploadFile, _downloadFile, value.tier),
        email: value.email ? candid_some(value.email) : candid_none()
    };
}
function to_candid_record_n43(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    maxCustomLists?: bigint;
    maxTasks?: bigint;
    maxRoutines?: bigint;
}): {
    maxCustomLists: [] | [bigint];
    maxTasks: [] | [bigint];
    maxRoutines: [] | [bigint];
} {
    return {
        maxCustomLists: value.maxCustomLists ? candid_some(value.maxCustomLists) : candid_none(),
        maxTasks: value.maxTasks ? candid_some(value.maxTasks) : candid_none(),
        maxRoutines: value.maxRoutines ? candid_some(value.maxRoutines) : candid_none()
    };
}
function to_candid_record_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    category: string;
    amount: number;
    spendType: SpendType;
}): {
    category: string;
    amount: number;
    spendType: _SpendType;
} {
    return {
        category: value.category,
        amount: value.amount,
        spendType: to_candid_SpendType_n7(_uploadFile, _downloadFile, value.spendType)
    };
}
function to_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
function to_candid_variant_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: RoutineSection): {
    top: null;
} | {
    bottom: null;
} {
    return value == RoutineSection.top ? {
        top: null
    } : value == RoutineSection.bottom ? {
        bottom: null
    } : value;
}
function to_candid_variant_n41(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserTier): {
    gold: null;
} | {
    diamond: null;
} | {
    basic: null;
} | {
    silver: null;
} {
    return value == UserTier.gold ? {
        gold: null
    } : value == UserTier.diamond ? {
        diamond: null
    } : value == UserTier.basic ? {
        basic: null
    } : value == UserTier.silver ? {
        silver: null
    } : value;
}
function to_candid_variant_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: SpendType): {
    normal: null;
} | {
    preDeducted: null;
} {
    return value == SpendType.normal ? {
        normal: null
    } : value == SpendType.preDeducted ? {
        preDeducted: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
