/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface List {
  'id' : ListId,
  'name' : string,
  'important' : boolean,
  'urgent' : boolean,
  'quadrant' : boolean,
}
export type ListId = bigint;
export interface MonetarySettings {
  'maxDailyPriorities' : bigint,
  'maxMorningRoutine' : bigint,
  'maxMoneyPerDay' : bigint,
  'totalBalance' : bigint,
  'maxEveningRoutine' : bigint,
}
export interface MorningRoutine {
  'id' : RoutineId,
  'weight' : bigint,
  'strikeCount' : bigint,
  'order' : bigint,
  'text' : string,
  'completed' : boolean,
  'section' : RoutineSection,
  'streakCount' : bigint,
}
export interface PayrollRecord {
  'total' : bigint,
  'submitted' : boolean,
  'date' : bigint,
  'details' : { 'morning' : bigint, 'evening' : bigint, 'priorities' : bigint },
}
export type RoutineId = bigint;
export type RoutineSection = { 'top' : null } |
  { 'bottom' : null };
export type SpendId = bigint;
export interface SpendInput {
  'category' : string,
  'amount' : number,
  'spendType' : SpendType,
}
export interface SpendPreset {
  'id' : bigint,
  'name' : string,
  'category' : string,
  'amount' : number,
}
export interface SpendRecord {
  'id' : SpendId,
  'date' : bigint,
  'category' : string,
  'amount' : number,
  'spendType' : SpendType,
}
export type SpendType = { 'normal' : null } |
  { 'preDeducted' : null };
export interface StorageMetrics {
  'totalTasks' : bigint,
  'estimatedHeapMemoryBytes' : bigint,
  'totalRoutines' : bigint,
  'totalUsers' : bigint,
  'estimatedStableMemoryBytes' : bigint,
}
export interface Task {
  'id' : TaskId,
  'weight' : number,
  'title' : string,
  'isLongTask' : boolean,
  'order' : bigint,
  'completed' : boolean,
  'description' : string,
  'important' : boolean,
  'urgent' : boolean,
  'listId' : ListId,
}
export interface TaskCreateInput {
  'title' : string,
  'isLongTask' : boolean,
  'order' : bigint,
  'description' : string,
  'important' : boolean,
  'urgent' : boolean,
  'listId' : ListId,
}
export type TaskId = bigint;
export interface TaskUpdateInput {
  'title' : string,
  'isLongTask' : boolean,
  'order' : bigint,
  'completed' : boolean,
  'description' : string,
  'important' : boolean,
  'urgent' : boolean,
  'listId' : ListId,
}
export interface TierLimits {
  'maxCustomLists' : [] | [bigint],
  'maxTasks' : [] | [bigint],
  'maxRoutines' : [] | [bigint],
}
export interface TierLimitsConfig {
  'gold' : TierLimits,
  'diamond' : TierLimits,
  'basic' : TierLimits,
  'silver' : TierLimits,
}
export interface UserMetadata {
  'principal' : Principal,
  'isAdmin' : boolean,
  'profile' : [] | [UserProfile],
}
export interface UserProfile {
  'earningsEnabled' : boolean,
  'name' : string,
  'tier' : UserTier,
  'email' : [] | [string],
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface UserStorageBreakdown {
  'principal' : Principal,
  'routineCount' : bigint,
  'taskCount' : bigint,
  'estimatedSizeBytes' : bigint,
}
export type UserTier = { 'gold' : null } |
  { 'diamond' : null } |
  { 'basic' : null } |
  { 'silver' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addPayroll' : ActorMethod<[bigint], bigint>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'completeMorningRoutine' : ActorMethod<[RoutineId, boolean], undefined>,
  'completeTask' : ActorMethod<[TaskId, boolean], undefined>,
  'createList' : ActorMethod<[string], ListId>,
  'createMorningRoutine' : ActorMethod<[string, RoutineSection], RoutineId>,
  'createPreset' : ActorMethod<[SpendPreset], bigint>,
  'createSpend' : ActorMethod<[SpendInput], string>,
  'createTask' : ActorMethod<[TaskCreateInput], TaskId>,
  'deleteList' : ActorMethod<[ListId], undefined>,
  'deleteMorningRoutine' : ActorMethod<[RoutineId], undefined>,
  'deletePreset' : ActorMethod<[bigint], undefined>,
  'deleteSpend' : ActorMethod<[SpendId], undefined>,
  'deleteTask' : ActorMethod<[TaskId], undefined>,
  'editPayrollLog' : ActorMethod<[bigint, bigint], undefined>,
  'ensureAllQuadrants' : ActorMethod<[], undefined>,
  'getAllLists' : ActorMethod<[], Array<List>>,
  'getAllMorningRoutines' : ActorMethod<[], Array<MorningRoutine>>,
  'getAllSpendPresets' : ActorMethod<[], Array<SpendPreset>>,
  'getAllSpends' : ActorMethod<[], Array<SpendRecord>>,
  'getAllTasks' : ActorMethod<[], Array<Task>>,
  'getAllTasksByList' : ActorMethod<[ListId], Array<Task>>,
  'getAllTierLimits' : ActorMethod<[], TierLimitsConfig>,
  'getAllUserMetadata' : ActorMethod<[], Array<[Principal, UserProfile]>>,
  'getAllUserMetadataWithRoles' : ActorMethod<[], Array<UserMetadata>>,
  'getAllUserStorageBreakdowns' : ActorMethod<[], Array<UserStorageBreakdown>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getDefaultOrder' : ActorMethod<[], bigint>,
  'getDefaultPosition' : ActorMethod<[], bigint>,
  'getEarningsEnabled' : ActorMethod<[], boolean>,
  'getEstimatedMemoryUsage' : ActorMethod<
    [],
    { 'stableSize' : bigint, 'heapSize' : bigint }
  >,
  'getList' : ActorMethod<[ListId], List>,
  'getMonetarySettings' : ActorMethod<[], MonetarySettings>,
  'getMorningRoutine' : ActorMethod<[RoutineId], MorningRoutine>,
  'getMorningRoutinesBySection' : ActorMethod<
    [RoutineSection],
    Array<MorningRoutine>
  >,
  'getOverallStorageMetrics' : ActorMethod<[], StorageMetrics>,
  'getPayrollHistory' : ActorMethod<[], Array<PayrollRecord>>,
  'getPreset' : ActorMethod<[bigint], [] | [SpendPreset]>,
  'getRoutineAndTaskStorageBreakdown' : ActorMethod<
    [],
    {
      'tasks' : { 'total' : bigint, 'userBreakdowns' : Array<bigint> },
      'routines' : { 'total' : bigint, 'userBreakdowns' : Array<bigint> },
    }
  >,
  'getRoutineStorageBreakdown' : ActorMethod<
    [],
    { 'total' : bigint, 'userBreakdowns' : Array<bigint> }
  >,
  'getTask' : ActorMethod<[TaskId], Task>,
  'getTaskStorageBreakdown' : ActorMethod<
    [],
    { 'total' : bigint, 'userBreakdowns' : Array<bigint> }
  >,
  'getTopUsersByStorage' : ActorMethod<[bigint], Array<UserStorageBreakdown>>,
  'getTotalStorageUsed' : ActorMethod<[], bigint>,
  'getTotalUsers' : ActorMethod<[], bigint>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'moveTaskToList' : ActorMethod<[TaskId, ListId, bigint], undefined>,
  'promoteToAdmin' : ActorMethod<[Principal], undefined>,
  'removeAdmin' : ActorMethod<[Principal], undefined>,
  'resetNewDay' : ActorMethod<[Array<RoutineId>], undefined>,
  'resetSkippedDay' : ActorMethod<[], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'saveMonetarySettings' : ActorMethod<[MonetarySettings], undefined>,
  'setUserTier' : ActorMethod<[Principal, UserTier], undefined>,
  'submitPayrollLog' : ActorMethod<[bigint], bigint>,
  'toggleEarningsSystem' : ActorMethod<[boolean], boolean>,
  'updateMorningRoutine' : ActorMethod<
    [RoutineId, string, RoutineSection],
    undefined
  >,
  'updatePreset' : ActorMethod<[bigint, SpendPreset], undefined>,
  'updateRoutineItemPosition' : ActorMethod<[RoutineId, bigint], undefined>,
  'updateTask' : ActorMethod<[TaskId, TaskUpdateInput], undefined>,
  'updateTierLimits' : ActorMethod<[UserTier, TierLimits], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];